--- !ruby/object:Role
concise_attributes:
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: name
  value_before_type_cast: admin
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: id
  value_before_type_cast: 9f48c74d-43ef-4c8e-abc2-1c64f46fb75a
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: resource_id
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: resource_type
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: 2019-07-11 12:45:01.911179000 Z
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: 2019-07-11 12:45:01.911179000 Z
new_record: false
active_record_yaml_version: 2
